spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/planpnae
    username: planpnae
    password: planpnae
server:
  port: 8089
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
