spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/hb_student_tracker
    username: hbstudent
    password: hbstudent
server:
  port: 8089
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
